{{- if or .Values.postgresql.enabled .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thread-platform.fullname" . }}-connections
  labels: {{- include "thread-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  postgres-url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ printf "redis://:%s@%s-redis-master:6379" .Values.redis.auth.password .Release.Name | quote }}
  {{- end }}
{{- end }}
